# Generated by Django 5.2.5 on 2025-08-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='media/imagens/anuncios/'),
        ),
    ]
