# Generated by Django 5.2.5 on 2025-08-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estado',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado'), ('Seminovo', 'Seminovo')], default='Novo', max_length=100),
        ),
    ]
