# Generated by Django 5.2.5 on 2025-08-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_alter_anuncio_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagem',
            field=models.ImageField(upload_to='imagens/anuncios/'),
        ),
    ]
